# Generated by Django 4.2.1 on 2023-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_purchaselist_logistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageitems',
            name='return_delivery_charge',
            field=models.IntegerField(default=0),
        ),
    ]
