# Generated by Django 4.2.4 on 2023-08-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_items_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='website/'),
        ),
    ]
