# Generated by Django 4.2.4 on 2023-09-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_promotionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_one', models.CharField(blank=True, max_length=225)),
                ('text_two', models.CharField(blank=True, max_length=225)),
                ('slide_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='promotionitem',
            name='promo_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
